#' Example multi-site dataset for dsPCAdriversClient
#'
#' A small simulated multi-site dataset used in the package examples, unit
#' tests and vignette. It mimics the structure expected by a DataSHIELD
#' federated analysis: separate expression and clinical tables per site, with
#' sample identifiers shared across the two tables of the same site.
#'
#' The dataset is intentionally small to keep the installed package size
#' within CRAN limits. Two simulated biological effects are embedded in the
#' expression data so that \code{ds.plotDrivers} produces non-trivial output:
#'
#' \itemize{
#'   \item Disease signal: cases upregulate the first 15 genes (+2 on the log scale).
#'   \item Batch effect: the first 8 genes are shifted by batch (batch 1/2/3 x 0.5).
#' }
#'
#' @format A named list of length 2 (\code{site1}, \code{site2}). Each element
#' is itself a list with two data frames:
#' \describe{
#'   \item{expr}{Numeric data frame of simulated log-scale expression values in
#'   samples x genes orientation, as required by \code{dssPrincomp} (which
#'   computes the covariance across columns). 60 rows for \code{site1} and 50
#'   for \code{site2}, both with 30 gene columns named \code{gene_1} ...
#'   \code{gene_30}. Row names are the sample identifiers \code{sample_1} ...
#'   \code{sample_n}.}
#'   \item{clinical}{Data frame of 7 simulated clinical variables with one row
#'   per sample, matching the rows of \code{expr} via the \code{sample_id}
#'   column. Columns are: \code{sample_id} (character), \code{age} (numeric),
#'   \code{sex} (character, "M"/"F"), \code{batch} (factor with three levels),
#'   \code{disease_status} (character, "case"/"control"), \code{bmi}
#'   (numeric) and \code{smoking} (character, "never"/"former"/"current").}
#' }
#'
#' @source Generated by \code{data-raw/generate_example_data.R}. Re-run that
#' script from the package root to regenerate \code{data/site_data.rda}.
#'
#' @usage NULL
"site_data"
